export { default as DashboardPage } from './DashboardPage/DashboardPage';
export { default as ForgetPasswordTemplate } from './ForgetPasswordTemplate/ForgetPasswordTemplate';
// import { default as DeletePage } from './GlobalTemplate/DeletePage';
export { default as HomePage } from './HomePage/HomePage';
export { default as InitiativeCreationTemplate } from './InitiativeCreationTemplate/InitiativeCreationTemplate';
export { default as LegacyPolicyTemplate } from './LegacyPolicyTemplate/LegacyPolicyTemplate';
export { default as LegalNoticesTemplate } from './LegalNoticesTemplate/LegalNoticesTemplate';
export { default as MapViewTemplate } from './MapViewTemplate/MapViewTemplate';
export { default as RegisterTemplate } from './RegisterTemplate/RegisterTemplate';
export { default as ResetPasswordTemplate } from './ResetPasswordTemplate/ResetPasswordTemplate';
export { default as SignInTemplate } from './SignInTemplate/SignInTemplate';
