version: "3.8"
services:
  climate-db:
    image: postgres:12.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: climate-db
      POSTGRES_USER: climate-db
      POSTGRES_PASSWORD: climate-db
    volumes:
      - climate-postgres-data:/var/lib/postgresql/data

  web:
    image: node:22-alpine
    container_name: climate-web
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - climate-db

volumes:
  climate-postgres-data:
