import { Region } from '@/types/Regions';

export const regions: Region[] = [
  {
    id: 'auvergne-rhone-alpes',
    region: 'Auvergne-Rhône-Alpes',
    emoji: '⛰️',
    count: 0,
    depts: [
      { num: '01', name: 'Ain', count: 0 },
      { num: '03', name: 'Allier', count: 0 },
      { num: '07', name: 'Ardèche', count: 0 },
      { num: '15', name: 'Cantal', count: 0 },
      { num: '26', name: 'Drôme', count: 0 },
      { num: '38', name: 'Isère', count: 0 },
      { num: '42', name: 'Loire', count: 0 },
      { num: '43', name: 'Haute-Loire', count: 0 },
      { num: '63', name: 'Puy-de-Dôme', count: 0 },
      { num: '69', name: 'Rhône', count: 0 },
      { num: '73', name: 'Savoie', count: 0 },
      { num: '74', name: 'Haute-Savoie', count: 0 },
    ],
  },
  {
    id: 'bourgogne-franche-comte',
    region: 'Bourgogne-Franche-Comté',
    emoji: '🍷',
    count: 0,
    depts: [
      { num: '21', name: "Côte-d'Or", count: 0 },
      { num: '25', name: 'Doubs', count: 0 },
      { num: '39', name: 'Jura', count: 0 },
      { num: '58', name: 'Nièvre', count: 0 },
      { num: '70', name: 'Haute-Saône', count: 0 },
      { num: '71', name: 'Saône-et-Loire', count: 0 },
      { num: '89', name: 'Yonne', count: 0 },
    ],
  },
  {
    id: 'bretagne',
    region: 'Bretagne',
    emoji: '🌊',
    count: 0,
    depts: [
      { num: '22', name: "Côtes-d'Armor", count: 0 },
      { num: '29', name: 'Finistère', count: 0 },
      { num: '35', name: 'Ille-et-Vilaine', count: 0 },
      { num: '56', name: 'Morbihan', count: 0 },
    ],
  },
  {
    id: 'centre-val-de-loire',
    region: 'Centre-Val de Loire',
    emoji: '🏰',
    count: 0,
    depts: [
      { num: '18', name: 'Cher', count: 0 },
      { num: '28', name: 'Eure-et-Loir', count: 0 },
      { num: '36', name: 'Indre', count: 0 },
      { num: '37', name: 'Indre-et-Loire', count: 0 },
      { num: '41', name: 'Loir-et-Cher', count: 0 },
      { num: '45', name: 'Loiret', count: 0 },
    ],
  },
  {
    id: 'grand-est',
    region: 'Grand Est',
    emoji: '🥨',
    count: 0,
    depts: [
      { num: '08', name: 'Ardennes', count: 0 },
      { num: '10', name: 'Aube', count: 0 },
      { num: '51', name: 'Marne', count: 0 },
      { num: '52', name: 'Haute-Marne', count: 0 },
      { num: '54', name: 'Meurthe-et-Moselle', count: 0 },
      { num: '55', name: 'Meuse', count: 0 },
      { num: '57', name: 'Moselle', count: 0 },
      { num: '67', name: 'Bas-Rhin', count: 0 },
      { num: '68', name: 'Haut-Rhin', count: 0 },
      { num: '88', name: 'Vosges', count: 0 },
    ],
  },
  {
    id: 'hauts-de-france',
    region: 'Hauts-de-France',
    emoji: '🌾',
    count: 0,
    depts: [
      { num: '02', name: 'Aisne', count: 0 },
      { num: '59', name: 'Nord', count: 0 },
      { num: '60', name: 'Oise', count: 0 },
      { num: '62', name: 'Pas-de-Calais', count: 0 },
      { num: '80', name: 'Somme', count: 0 },
    ],
  },
  {
    id: 'ile-de-france',
    region: 'Île-de-France',
    emoji: '🗼',
    count: 0,
    depts: [
      { num: '75', name: 'Paris', count: 0 },
      { num: '77', name: 'Seine-et-Marne', count: 0 },
      { num: '78', name: 'Yvelines', count: 0 },
      { num: '91', name: 'Essonne', count: 0 },
      { num: '92', name: 'Hauts-de-Seine', count: 0 },
      { num: '93', name: 'Seine-Saint-Denis', count: 0 },
      { num: '94', name: 'Val-de-Marne', count: 0 },
      { num: '95', name: "Val-d'Oise", count: 0 },
    ],
  },
  {
    id: 'normandie',
    region: 'Normandie',
    emoji: '🐄',
    count: 0,
    depts: [
      { num: '14', name: 'Calvados', count: 0 },
      { num: '27', name: 'Eure', count: 0 },
      { num: '50', name: 'Manche', count: 0 },
      { num: '61', name: 'Orne', count: 0 },
      { num: '76', name: 'Seine-Maritime', count: 0 },
    ],
  },
  {
    id: 'nouvelle-aquitaine',
    region: 'Nouvelle-Aquitaine',
    emoji: '🌊',
    count: 0,
    depts: [
      { num: '16', name: 'Charente', count: 0 },
      { num: '17', name: 'Charente-Maritime', count: 0 },
      { num: '19', name: 'Corrèze', count: 0 },
      { num: '23', name: 'Creuse', count: 0 },
      { num: '24', name: 'Dordogne', count: 0 },
      { num: '33', name: 'Gironde', count: 0 },
      { num: '40', name: 'Landes', count: 0 },
      { num: '47', name: 'Lot-et-Garonne', count: 0 },
      { num: '64', name: 'Pyrénées-Atlantiques', count: 0 },
      { num: '79', name: 'Deux-Sèvres', count: 0 },
      { num: '86', name: 'Vienne', count: 0 },
      { num: '87', name: 'Haute-Vienne', count: 0 },
    ],
  },
  {
    id: 'occitanie',
    region: 'Occitanie',
    emoji: '☀️',
    count: 0,
    depts: [
      { num: '09', name: 'Ariège', count: 0 },
      { num: '11', name: 'Aude', count: 0 },
      { num: '12', name: 'Aveyron', count: 0 },
      { num: '30', name: 'Gard', count: 0 },
      { num: '31', name: 'Haute-Garonne', count: 0 },
      { num: '32', name: 'Gers', count: 0 },
      { num: '34', name: 'Hérault', count: 0 },
      { num: '46', name: 'Lot', count: 0 },
      { num: '48', name: 'Lozère', count: 0 },
      { num: '65', name: 'Hautes-Pyrénées', count: 0 },
      { num: '66', name: 'Pyrénées-Orientales', count: 0 },
      { num: '81', name: 'Tarn', count: 0 },
      { num: '82', name: 'Tarn-et-Garonne', count: 0 },
    ],
  },
  {
    id: 'pays-de-la-loire',
    region: 'Pays de la Loire',
    emoji: '🌿',
    count: 0,
    depts: [
      { num: '44', name: 'Loire-Atlantique', count: 0 },
      { num: '49', name: 'Maine-et-Loire', count: 0 },
      { num: '53', name: 'Mayenne', count: 0 },
      { num: '72', name: 'Sarthe', count: 0 },
      { num: '85', name: 'Vendée', count: 0 },
    ],
  },
  {
    id: 'paca',
    region: "Provence-Alpes-Côte d'Azur",
    emoji: '🌻',
    count: 0,
    depts: [
      { num: '04', name: 'Alpes-de-Haute-Provence', count: 0 },
      { num: '05', name: 'Hautes-Alpes', count: 0 },
      { num: '06', name: 'Alpes-Maritimes', count: 0 },
      { num: '13', name: 'Bouches-du-Rhône', count: 0 },
      { num: '83', name: 'Var', count: 0 },
      { num: '84', name: 'Vaucluse', count: 0 },
    ],
  },
  {
    id: 'corse',
    region: 'Corse',
    emoji: '🏝️',
    count: 0,
    depts: [
      { num: '2A', name: 'Corse-du-Sud', count: 0 },
      { num: '2B', name: 'Haute-Corse', count: 0 },
    ],
  },
];

export const NUMBER_OF_REGIONS = 13;
